package gui;

import java.awt.Color;
import java.util.List;

import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import custom.barChart.Chart;
import custom.barChart.ModelChart;
import custom.barChart.PanelShadow;
import custom.barChart.ScrollChart;
import custom.barChart.ThongKeBanChay;
import custom.barChart.ThongKeTonKho;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

public class BieuDoTonKho extends JPanel{
	private PanelShadow pnlShadow;
    public BieuDoTonKho() {
    	setSize(1080, 300);
		setVisible(true);
        initComponents();
        chart.start();
    }
    
    
    public void ThongKeKho(List<ThongKeTonKho> danhSach) {
    	chart.clear();
    	initComponents();
    	int size = danhSach.size();
    	double[] arr = new double[size];
    	int i = 0;
    	for (ThongKeTonKho soLuong : danhSach) {
    		arr[i++] = (double)soLuong.getTongSoLuong(); 
    	}
    	
    	for (ThongKeTonKho soLuong : danhSach) {
    		chart.addLegend(soLuong.getMaSP(), new Color(randomIntColor(),randomIntColor(), randomIntColor()));
    	}
		chart.addData(new ModelChart("",arr ));
    	chart.start();
    	
    	
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlShadow = new PanelShadow();
        pnlShadow.setShadowColor(new Color(65, 105, 225));
        pnlShadow.setShadowSize(2);
        chart = new ScrollChart();
        
        pnlShadow.setBackground(new java.awt.Color(255, 255, 255));
        pnlShadow.setBorder(new EmptyBorder(10, 10, 10, 10));
        pnlShadow.setColorGradient(new Color(255, 255, 255));


        chart.setForeground(Color.BLACK);

        javax.swing.GroupLayout pnlShadowLayout = new javax.swing.GroupLayout(pnlShadow);
        pnlShadowLayout.setHorizontalGroup(
        	pnlShadowLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlShadowLayout.createSequentialGroup()
        			.addComponent(chart, GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        			.addContainerGap())
        );
        pnlShadowLayout.setVerticalGroup(
        	pnlShadowLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlShadowLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(chart, GroupLayout.PREFERRED_SIZE, 310, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(25, Short.MAX_VALUE))
        );
        pnlShadow.setLayout(pnlShadowLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlShadow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlShadow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        chart.start();
    }//GEN-LAST:event_formWindowOpened


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BieuDoBanChay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BieuDoBanChay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BieuDoBanChay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BieuDoBanChay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ScrollChart chart;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    private int randomIntColor() {
    	double randomDouble = Math.random();
        randomDouble = randomDouble * 255 + 0;
        return (int) randomDouble;
    }
    
}
